#!/bin/sh
/c/Program\ Files\ \(x86\)/nodejs/node_modules/less/bin/lessc /f/wamp/www/invictus.com/app/public/css/common/all.less > /f/wamp/www/invictus.com/app/public/css/common/all.css -x --yui-compressor
/c/Program\ Files\ \(x86\)/nodejs/node_modules/less/bin/lessc /f/wamp/www/invictus.com/app/public/css/invictus/all.less > /f/wamp/www/invictus.com/app/public/css/invictus/all.css 